### PR TITLE
added models and initial api routes

### PR DESCRIPTION
**Pull request by jmdahle**
Added models for Smothii, Ingredients, & Recipes.
Added a seeds.sql file in the model directory for adding sample data to work with.
Added api routes (which you can call to see the data returned at any of the routes)

Example: localhost:3000/api/smoothies

### CODE REVIEW

**Comment by SaraMc12** [comment]
woop woop

**Comment by jmdahle** [comment]
Reopening.

**Comment by SaraMc12** [comment]
approved

**Comment by SaraMc12** [comment]
Woo!

**Pull request merged**
